name: calculator
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^4.0.2
  grpc: ^2.1.3
  protobuf: ^1.0.1
  yaml: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/config.yaml

