apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: grpc-flutter-web-example
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.TAG}}"
  artifacts:
  - image: server
    docker:
      dockerfile: package/server/Dockerfile
    sync:
      infer:
        - 'server/cmd/*.go'
        - 'server/pkg/reversepb/*.go'
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s/server/*.yaml
