apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: grpc-flutter-web-example
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.TAG}}"
  artifacts:
  - image: flutter
    docker:
      dockerfile: package/flutter/Dockerfile
  - image: client
    docker:
      dockerfile: package/client/Dockerfile
    sync:
      infer:
        - 'client/cmd/*.go'
        - 'client/pubspec.yaml'
        - 'client/lib/*.dart'
        - 'client/lib/services/*.dart'
        - 'client/lib/services/src/generated/*.dart'
  - image: server
    docker:
      dockerfile: package/server/Dockerfile
    sync:
      infer:
        - 'server/cmd/*.go'
        - 'server/pkg/reversepb/*.go'
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s/server/*.yaml
    - k8s/client/*.yaml
